apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-role
  namespace: default
rules: 
  # - apiGroups: ["", ""] Aqui nos inserimos os apiGroups que queremos como referencia, como exemplo, outro caso seria inserir os API groups que precisam estar sendo utilizados.
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "create", "get"]
