apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec: 
  replicas: 4
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80 
      affinity: 
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:   
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: nginx
              topologyKey: "region"
              #topologykey: "kubernetes.io/hostname"
              #
              #
              #outra opcao 
              #affinity:
              #podAntiAffinity:
              #requiredDuringSchedulingIgnoredDuringExecution:
              #- labelSelector:
              #    matchLabels:
              #     app: nginx:
              #  topologykey: "region"
