apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.service.name }}
spec:
  selector:
    app: {{ .Values.redis.labels.app }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIp
