apiVersion: v1
kind: Secret
metadata: 
  name: dockerhub
type: kubernetes.io/dockerconfigjason
data:
  .dockerconfigjson: |
    ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlpHVnFiMjFoT21SamEzSmZjR0YwWDBVM1UyNWpjMkZmUmxaUU4wbDVaRlJtZVdSTlYwSmxja0UyY3c9PSIKCQl9Cgl9Cn0=

